#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jsch
Version  : 0.1.44.1
Release  : 1
URL      : https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.44-1/jsch-0.1.44-1.jar
Source0  : https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.44-1/jsch-0.1.44-1.jar
Source1  : https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.44-1/jsch-0.1.44-1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-jsch-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-jsch package.
Group: Data

%description data
data components for the mvn-jsch package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/jcraft/jsch/0.1.44-1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/jcraft/jsch/0.1.44-1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/jcraft/jsch/0.1.44-1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/jcraft/jsch/0.1.44-1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/jcraft/jsch/0.1.44-1/jsch-0.1.44-1.jar
/usr/share/java/.m2/repository/com/jcraft/jsch/0.1.44-1/jsch-0.1.44-1.pom
